version: "3"
services:
  postgres:
    image: postgres:15-alpine
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    restart: always

volumes:
  postgres-data:
    driver: local
