version: "3"
services:
  postgres:
    image: postgres:alpine
    command: postgres -c 'max_connections=2000'
    networks:
        - bruno
    ports:
        - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: postgres
    restart: always

networks:
  bruno:

volumes:
  postgres-data: